- src/services/penaltyDocuments.js
- src/utils/createSimpleResponse.js
- src/validationModels/penaltyValidation.js
Removed validation restrictions on updateMulti.
> Fix updateMulti validation restrictions

- src/services/penaltyDocuments.js
- src/utils/createSimpleResponse.js
if no results returned would error. fix to return empty array.
> fix getDcouments failing when nothing to return and remove console logs

- src/functions/list.js
- src/services/penaltyDocuments.js
- src/validationModels/penaltyValidation.js
Refactored batch fetching to use query instead of scan.
> Refactor batch fetching to user query

- src/services/penaltyDocuments.js
- src/utils/formatMinimalDocument.js
Ensure origin is stamped on new documents both on create and updateDocuments.
Fixed some issues with getting by Token.
> Stamp origin with app on create

- src/functions/updateWithPayment.js
- src/utils/formatMinimalDocument.js
Fixing issue where payments aren't updating penaltyDocuments via lambda invocation.
> Fix extracting data from payload

- src/functions/updateWithPayment.js
- src/services/penaltyDocuments.js
Fix some token stuff and handle push notifications for Payments
> Modify penalty document notifications

- src/functions/updateWithPayment.js
- src/services/penaltyDocuments.js
- src/utils/mergeDocumentsWithPayments.js
- src/utils/time.js
create dummy document when payment made and no doc exists
> rsp969 - create penaltyDocument if payment received and no doc exists

- src/functions/updateUponPaymentDelete.js
- src/handler.js
- src/services/penaltyDocuments.js
Send notification if payment made (when original document is offline) and the phone comes back online.
Create new function to be called by payments service to update document when payment reverted.
> Develop rsp969 send notification

- src/services/penaltyDocuments.js
- src/utils/mergeDocumentsWithPayments.js
ensure payment method retrieved in penaltyDocuments service.
> Develop add payment method

- src/services/penaltyDocuments.js
Please forgive this filthy abomination, it's the only way the invocation would work 😭
> Fix batchfetch invocation

- src/services/penaltyDocuments.js
- src/services/penaltyGroups.js
* Make DynamoDB batch size configurable through env var (default 75)
* Make penalty group payload validation configurable
> Add configuration of penalty group behaviours to aid development process

- package-lock.json
- package.json
- src/services/joi.unit.js
Changes made in validation package. Simply bumping version and adding test.
- https://github.com/dvsa/rsp-validation-package/pull/15
- https://github.com/dvsa/rsp-validation-package/pull/16
> RSP-1521: Penalty document timestamp

- serverless/serverless.yml
- src/functions/stream.js
- src/handler.js
- src/services/penaltyDocuments.js
- src/services/penaltyDocuments.unit.js
Add back streamDocuments (removed in 347f5a6)
> RSP-1569: Fix silent notifications

- src/services/penaltyDocuments.js
- src/services/penaltyGroups.js
Leads on from https://github.com/dvsa/rsp-documents-service/pull/64, removing badge in SNS payload
> RSP-1569: Silent notifications

- .babelrc
- serverless/serverless.yml
> rsp-1917: upgrade node runtime

- README.md
- src/config.js
Added more instructions to help start running locally.
Related issue: n/a
> feat:Feature/update readme

- mock-data/fake-penalty-groups.json
- mock-data/fake-penalty-notice.json
Added fresh mock data.  
Related issue: [RSP-2042](https://dvsa.atlassian.net/browse/RSP-2042)
> Feature(mock-data):add mock data

- .github/workflows/ci.yml
- .github/workflows/update-code.yaml
- lambdas.json
- webpack.production.js
- New step in workflow to update lambda function code on AWS
- Using DVSA update function code action
Related issue: [RSP-2083](https://dvsa.atlassian.net/browse/RSP-2083)
> feat: New update lambda function code workflow

- package-lock.json
- package.json
- src/services/joi.unit.js
- src/services/penaltyDocuments.js
- src/services/penaltyGroups.js
- Added new dependency entry to package.json
- Removed old dependency entry from package.json
- Edited unit test files to use new validation package
- Edited two js files to use new validation package
Related issue: [RSP-2106](https://dvsa.atlassian.net/browse/RSP-2106?atlOrigin=eyJpIjoiMDQzMDViNzQ0YTVjNDdkNGFlMTgzZDFiMjEwMjViNDMiLCJwIjoiaiJ9)
> feat: Update validation package to 1.6.1, remove old version

- package-lock.json
- package.json
- Contains fix for returning proper validation error message
- Ticket RSP-2164
Related issue: [RSP-2164](RSP-2164)
> feat: Update DVSA Validation library to get latest

- README.md
Release-As: 4.0.1
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)
> fix: release 4.0.1

- .github/workflows/release.yaml
- README.md
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)
> Fix/release 4.0.1

- .github/workflows/release.yaml
release 4.0.2
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)
> Release/rc 4.0.2

- package-lock.json
fix dependancy
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)
> fix: dependancy for validation

- .github/workflows/ci.yml
- .github/workflows/release.yaml
- .github/workflows/update-code.yaml
- package-lock.json
Amended workflows for main not master
Related issue: n/a
> fix:updated workflows
